import { useStudio } from "../store";
import { RANKED, tierCuts } from "../data/mock";
import { surfaceHatch, hatch } from "../ui";
import type { Tier } from "../types";

const TIERS: Tier[] = ["5", "15", "30", "45"];

export function CurateScreen() {
  const { tier, setTier, nav } = useStudio();

  const tierBtn = (t: Tier): React.CSSProperties => ({
    padding: "8px 16px",
    borderRadius: 8,
    border: `1px solid ${tier === t ? "var(--accent)" : "var(--border)"}`,
    background: tier === t ? "var(--accent)" : "var(--surface-2)",
    color: tier === t ? "var(--accent-contrast)" : "var(--text-muted)",
    fontWeight: 600,
    fontSize: 13,
    cursor: "pointer",
  });

  return (
    <div style={{ padding: "22px 24px", maxWidth: 1080 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 16 }}>
        <span style={{ fontSize: 11, fontWeight: 600, color: "var(--ai)", border: "1px solid var(--ai)", borderRadius: 999, padding: "3px 10px" }}>✦ AI-curated</span>
        <span style={{ fontSize: 12.5, color: "var(--text-muted)" }}>Everything below was generated by reeltreat. Edit freely — your changes layer over the AI.</span>
        <div style={{ flex: 1 }} />
        <button style={{ padding: "8px 13px", borderRadius: 8, border: "1px solid var(--ai)", background: "rgba(167,139,250,.1)", color: "var(--ai)", fontSize: 12.5, cursor: "pointer" }}>↻ Re-run curation (1 AI call)</button>
      </div>
      <div style={{ fontFamily: "var(--mono)", fontSize: 11, color: "var(--text-faint)", marginBottom: 16 }}>✓ cached — no AI call needed unless shots change</div>

      <div style={{ background: "var(--surface)", border: "1px solid var(--ai)", borderRadius: 12, overflow: "hidden", marginBottom: 20, boxShadow: "0 0 0 3px rgba(167,139,250,.08)" }}>
        <div style={{ display: "grid", gridTemplateColumns: "1.3fr 1fr" }}>
          <div style={{ position: "relative", minHeight: 220, background: hatch(12) }}>
            <span style={{ position: "absolute", top: 12, left: 12, fontFamily: "var(--mono)", fontSize: 10.5, color: "rgba(255,255,255,.7)", background: "rgba(0,0,0,.4)", padding: "3px 8px", borderRadius: 5 }}>hero: dashboard</span>
            <div style={{ position: "absolute", bottom: 0, left: 0, right: 0, padding: "28px 22px 20px", background: "linear-gradient(transparent,rgba(0,0,0,.72))" }}>
              <div style={{ fontSize: 24, fontWeight: 700, letterSpacing: "-.02em", color: "#fff", lineHeight: 1.15, textShadow: "0 2px 12px rgba(0,0,0,.6)" }}>Your product's trailer — rendered in one click.</div>
            </div>
          </div>
          <div style={{ padding: 20 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 7, marginBottom: 10 }}><span style={{ color: "var(--ai)" }}>✦</span><span style={{ fontSize: 12.5, fontWeight: 600, color: "var(--ai)" }}>Tagline</span></div>
            <textarea defaultValue="Your product's trailer — rendered in one click." style={{ width: "100%", minHeight: 70, resize: "none", background: "var(--surface-2)", border: "1px solid var(--border)", borderRadius: 8, padding: "10px 12px", color: "var(--text)", fontSize: 14, fontFamily: "inherit", lineHeight: 1.4 }} />
            <div style={{ display: "flex", justifyContent: "space-between", marginTop: 6 }}><span style={{ fontSize: 11, color: "var(--text-faint)" }}>edited from AI: "Ship your product story in 15 seconds."</span><span style={{ fontFamily: "var(--mono)", fontSize: 11, color: "var(--text-faint)" }}>48/90</span></div>
            <div style={{ display: "flex", gap: 8, marginTop: 14 }}>
              <button style={{ padding: "8px 13px", borderRadius: 7, border: "1px solid var(--ai)", background: "rgba(167,139,250,.1)", color: "var(--ai)", fontSize: 12.5, cursor: "pointer" }}>✦ Regenerate</button>
              <button style={{ padding: "8px 13px", borderRadius: 7, border: "1px solid var(--border)", background: "var(--surface-2)", color: "var(--text)", fontSize: 12.5, cursor: "pointer" }}>Pick different hero</button>
            </div>
          </div>
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 300px", gap: 20, alignItems: "start" }}>
        <div>
          <div style={{ fontWeight: 600, fontSize: 14, marginBottom: 12 }}>Ranked shots</div>
          <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
            {RANKED.map((rk) => (
              <div key={rk.id} style={{ display: "flex", alignItems: "center", gap: 14, background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 10, padding: "12px 14px" }}>
                <span style={{ width: 26, height: 26, flex: "0 0 26px", borderRadius: 999, background: "var(--surface-2)", border: "1px solid var(--border)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--mono)", fontSize: 12, fontWeight: 600 }}>{rk.r}</span>
                <div style={{ width: 76, height: 46, flex: "0 0 76px", borderRadius: 6, background: surfaceHatch(8), border: "1px solid var(--border)" }} />
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontFamily: "var(--mono)", fontSize: 11.5, color: "var(--text-faint)", marginBottom: 4 }}>{rk.id}</div>
                  <input defaultValue={rk.callout} maxLength={40} style={{ width: "100%", maxWidth: 260, background: "var(--surface-2)", border: "1px solid var(--border)", borderRadius: 6, padding: "6px 9px", color: "var(--text)", fontSize: 13, fontWeight: 500 }} />
                </div>
                <div style={{ flex: 1, fontSize: 12, color: "var(--text-muted)", maxWidth: 220 }}>{rk.reason}</div>
                <span style={{ color: "var(--ai)", fontSize: 13 }}>✦</span>
              </div>
            ))}
          </div>

          <div style={{ marginTop: 16, border: "1px dashed var(--border)", borderRadius: 10, padding: 14, background: "var(--surface)" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10 }}><span style={{ fontSize: 11, letterSpacing: ".05em", textTransform: "uppercase", color: "var(--text-faint)" }}>Excluded from cut</span></div>
            <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
              <div style={{ width: 76, height: 46, borderRadius: 6, background: surfaceHatch(8), border: "1px solid var(--border)", opacity: 0.6 }} />
              <div style={{ flex: 1 }}><div style={{ fontFamily: "var(--mono)", fontSize: 12 }}>billing</div><div style={{ fontSize: 12, color: "var(--text-muted)" }}>Simple, transparent pricing</div></div>
              <button style={{ padding: "7px 13px", borderRadius: 7, border: "1px solid var(--accent)", background: "transparent", color: "var(--accent)", fontSize: 12.5, cursor: "pointer" }}>+ Re-add</button>
            </div>
          </div>
        </div>

        <div style={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 10, padding: 16, position: "sticky", top: 0 }}>
          <div style={{ fontWeight: 600, fontSize: 14, marginBottom: 4 }}>Cut length</div>
          <div style={{ fontSize: 12, color: "var(--text-muted)", marginBottom: 12 }}>AI orders shots to fill the tier.</div>
          <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
            {TIERS.map((t) => (
              <button key={t} onClick={() => setTier(t)} style={tierBtn(t)}>{t}s</button>
            ))}
          </div>
          <div style={{ fontSize: 11, letterSpacing: ".05em", textTransform: "uppercase", color: "var(--text-faint)", marginBottom: 8 }}>Ordered cut · {tier}s</div>
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            {tierCuts(tier).map((cu, i) => (
              <div key={i} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "8px 10px", background: "var(--surface-2)", border: "1px solid var(--border)", borderRadius: 7, fontSize: 12.5 }}><span style={{ fontFamily: "var(--mono)" }}>{cu.id}</span><span style={{ fontFamily: "var(--mono)", color: "var(--accent)" }}>{cu.sec}s</span></div>
            ))}
          </div>
          <button onClick={() => nav("frame")} style={{ width: "100%", marginTop: 16, padding: 10, borderRadius: 8, border: "none", background: "var(--accent)", color: "var(--accent-contrast)", fontWeight: 600, fontSize: 13, cursor: "pointer" }}>Continue to Edit →</button>
        </div>
      </div>
    </div>
  );
}
